apiVersion: batch/v1
kind: Job
metadata:
  name: preferred-replica-election
  namespace: kafka
spec:
  template:
    metadata:
      name: preferred-replica-election
    spec:
      containers:
      - name: kafka
        image: solsson/kafka:2.1.1@sha256:8bc8242c649c395ab79d76cc83b1052e63b4efea7f83547bf11eb3ef5ea6f8e1
        command:
        - ./bin/kafka-preferred-replica-election.sh
        - --zookeeper
        - zookeeper:2181
      restartPolicy: Never
  backoffLimit: 3
